cqwm:
  aliyun:
    oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
      bucketName: gcy-java-ai
      region: cn-beijing
  jwt:
    admin-secre-key: zxcvbnmlkjhgfdsaqwertyuiop123456
    admin-expiration: 36000000 # 3600 * 1000 * 10 10个小时
    user-secret-key: chenyifaer67373
    user-expiration: 36000000
    user-token-name: authentication
  wechat:
    appid: wx8e8ea679fe0fbdae
    secret: ef62e35ff3d9fd6d8eab7782b239e026
